name: bistro_shop
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used name: bistro_shopas CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Or whatever your current SDK version is

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.1
  image_picker: ^1.0.4
  flutter_stripe: ^11.5.0

  # Add these lines or ensure they are present and correctly indented
  google_sign_in: ^6.2.1 # Check pub.dev for the latest version
  http: ^1.4.0 # Check pub.dev for the latest version
  get: ^4.7.2
  fluttertoast: ^8.2.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0 # Or whatever version you have
